targetNamespace: ''
packages:
  - name: openai
    actions:
      - name: completion
        binary: false
        main: ''
        runtime: 'nodejs:default'
        web: true
        environment:
          apiKey: "${XXX}"
        limits:
          timeout: 30000
